# Generated by Django 2.2 on 2023-03-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MadlibDatabase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baseball',
        ),
        migrations.DeleteModel(
            name='BlindMice',
        ),
        migrations.DeleteModel(
            name='CatFiddle',
        ),
        migrations.DeleteModel(
            name='Fortune',
        ),
        migrations.DeleteModel(
            name='Greetings',
        ),
        migrations.DeleteModel(
            name='IndustryAward',
        ),
        migrations.DeleteModel(
            name='Katie',
        ),
        migrations.DeleteModel(
            name='NewDay',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='SickNote',
        ),
        migrations.DeleteModel(
            name='Tolkien',
        ),
        migrations.DeleteModel(
            name='Valentine',
        ),
        migrations.DeleteModel(
            name='VideoGame',
        ),
        migrations.DeleteModel(
            name='Yankee',
        ),
    ]
