# Generated by Django 2.2 on 2023-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MadlibDatabase', '0002_auto_20230306_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baseball_noun1', models.CharField(max_length=200)),
                ('Baseball_noun2', models.CharField(max_length=200)),
                ('Baseball_verb1', models.CharField(max_length=200)),
                ('Baseball_verb2', models.CharField(max_length=200)),
                ('Baseball_job1', models.CharField(max_length=200)),
                ('Baseball_number1', models.IntegerField()),
                ('Baseball_loc1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlindMice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlindMice_number1', models.IntegerField()),
                ('BlindMice_adj1', models.CharField(max_length=200)),
                ('BlindMice_verb1', models.CharField(max_length=200)),
                ('BlindMice_job1', models.CharField(max_length=200)),
                ('BlindMice_relation1', models.CharField(max_length=200)),
                ('BlindMice_part1', models.CharField(max_length=200)),
                ('BlindMice_noun1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatFiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatFiddle_word1', models.CharField(max_length=200)),
                ('CatFiddle_animal1', models.CharField(max_length=200)),
                ('CatFiddle_instrument1', models.CharField(max_length=200)),
                ('CatFiddle_adj1', models.CharField(max_length=200)),
                ('CatFiddle_adj2', models.CharField(max_length=200)),
                ('CatFiddle_noun1', models.CharField(max_length=200)),
                ('CatFiddle_noun2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fortune_verb1', models.CharField(max_length=200)),
                ('Fortune_verb2', models.CharField(max_length=200)),
                ('Fortune_adj1', models.CharField(max_length=200)),
                ('Fortune_adj2', models.CharField(max_length=200)),
                ('Fortune_adj3', models.CharField(max_length=200)),
                ('Fortune_noun1', models.CharField(max_length=200)),
                ('Fortune_noun2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Greetings_noun_plural1', models.CharField(max_length=200)),
                ('Greetings_occupation1', models.CharField(max_length=200)),
                ('Greetings_animal_plural1', models.CharField(max_length=200)),
                ('Greetings_adj1', models.CharField(max_length=200)),
                ('Greetings_place1', models.CharField(max_length=200)),
                ('Greetings_verb1', models.CharField(max_length=200)),
                ('Greetings_noun1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndustryAward_company1', models.CharField(max_length=200)),
                ('IndustryAward_noun1', models.CharField(max_length=200)),
                ('IndustryAward_noun2', models.CharField(max_length=200)),
                ('IndustryAward_noun3', models.CharField(max_length=200)),
                ('IndustryAward_noun4', models.CharField(max_length=200)),
                ('IndustryAward_adj1', models.CharField(max_length=200)),
                ('IndustryAward_adj2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Katie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Katie_verb1', models.CharField(max_length=200)),
                ('Katie_verb2', models.CharField(max_length=200)),
                ('Katie_verb3', models.CharField(max_length=200)),
                ('Katie_noun1', models.CharField(max_length=200)),
                ('Katie_part1', models.CharField(max_length=200)),
                ('Katie_animal1', models.CharField(max_length=200)),
                ('Katie_adj1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewDay_verb1', models.CharField(max_length=200)),
                ('NewDay_verb2', models.CharField(max_length=200)),
                ('NewDay_verb3', models.CharField(max_length=200)),
                ('NewDay_verb4', models.CharField(max_length=200)),
                ('NewDay_verb5', models.CharField(max_length=200)),
                ('NewDay_place1', models.CharField(max_length=200)),
                ('NewDay_adj1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pizza_name1', models.CharField(max_length=200)),
                ('Pizza_adj1', models.CharField(max_length=200)),
                ('Pizza_adj2', models.CharField(max_length=200)),
                ('Pizza_noun1', models.CharField(max_length=200)),
                ('Pizza_noun2', models.CharField(max_length=200)),
                ('Pizza_noun3', models.CharField(max_length=200)),
                ('Pizza_verb1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SickNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SickNote_word1', models.CharField(max_length=200)),
                ('SickNote_word2', models.CharField(max_length=200)),
                ('SickNote_name1', models.CharField(max_length=200)),
                ('SickNote_illness1', models.CharField(max_length=200)),
                ('SickNote_noun_plural1', models.CharField(max_length=200)),
                ('SickNote_adj1', models.CharField(max_length=200)),
                ('SickNote_adj2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tolkien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tolkien_fruit1', models.CharField(max_length=200)),
                ('Tolkien_noun1', models.CharField(max_length=200)),
                ('Tolkien_noun2', models.CharField(max_length=200)),
                ('Tolkien_noun3', models.CharField(max_length=200)),
                ('Tolkien_noun4', models.CharField(max_length=200)),
                ('Tolkien_noun5', models.CharField(max_length=200)),
                ('Tolkien_word1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Valentine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valentine_noun1', models.CharField(max_length=200)),
                ('Valentine_noun2', models.CharField(max_length=200)),
                ('Valentine_noun3', models.CharField(max_length=200)),
                ('Valentine_adj1', models.CharField(max_length=200)),
                ('Valentine_verb1', models.CharField(max_length=200)),
                ('Valentine_color1', models.CharField(max_length=200)),
                ('Valentine_part1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoGame_adj1', models.CharField(max_length=200)),
                ('VideoGame_adj2', models.CharField(max_length=200)),
                ('VideoGame_name1', models.CharField(max_length=200)),
                ('VideoGame_job1', models.CharField(max_length=200)),
                ('VideoGame_verb1', models.CharField(max_length=200)),
                ('VideoGame_noun1', models.CharField(max_length=200)),
                ('VideoGame_noun2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yankee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yankee_noun1', models.CharField(max_length=200)),
                ('Yankee_noun2', models.CharField(max_length=200)),
                ('Yankee_noun3', models.CharField(max_length=200)),
                ('Yankee_noun4', models.CharField(max_length=200)),
                ('Yankee_verb1', models.CharField(max_length=200)),
                ('Yankee_animal1', models.CharField(max_length=200)),
                ('Yankee_clothing1', models.CharField(max_length=200)),
                ('Yankee_adj1', models.CharField(max_length=200)),
            ],
        ),
    ]
